name: 每日调整广告提醒
on:
  schedule:
    # UTC时间 = 北京时间 - 8小时
    - cron: '0 1 * * *'    # 北京时间 09:00
    - cron: '0 10 * * *'   # 北京时间 18:00
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 发送钉钉提醒
        run: python "python dingding_reminder.py"
